#!/usr/bin/env node
/* Writes one page per project - formel.html, louvo.html, ... - so each project has its
   own address: rodarly.me/formel. Static hosts (GitHub Pages, Netlify, Cloudflare Pages)
   serve /formel from formel.html without any configuration.

   Every page is project.html with that project's title and description filled in, so a
   shared link previews the right project before any script runs; project.js reads the
   slug from the address. Re-run it after adding or renaming a project, or after editing
   project.html, and commit the result:

       node tools/build-pages.js

   Pages it wrote for a slug that no longer exists are deleted.
*/

"use strict";

const fs = require("fs");
const path = require("path");
const vm = require("vm");

const ROOT = path.join(__dirname, "..");
const MARK = "<!-- generated by tools/build-pages.js from project.html - do not edit -->";

function loadSite() {
  const code = fs.readFileSync(path.join(ROOT, "assets", "js", "data.js"), "utf8");
  const sandbox = { window: {} };
  vm.createContext(sandbox);
  vm.runInContext(code, sandbox);
  return sandbox.window.SITE || {};
}

function esc(text) {
  return String(text)
    .replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

const SITE = loadSite();
const template = fs.readFileSync(path.join(ROOT, "project.html"), "utf8");
const owner = (SITE.profile && SITE.profile.name) || "";
const RESERVED = new Set(["index", "project", "404"]);
const written = new Set();

(SITE.projects || []).forEach((project) => {
  const slug = project.slug;
  if (!/^[a-z0-9][a-z0-9-]*$/.test(slug || "") || RESERVED.has(slug)) {
    throw new Error('Project slug "' + slug + '" must be lowercase letters, digits and dashes, and not ' + [...RESERVED].join("/"));
  }

  const title = project.title + (owner ? " — " + owner : "");
  const description = project.pitch || project.summary || "";

  const html = template
    .replace(/<!DOCTYPE html>/i, (m) => m + "\n" + MARK)
    .replace(/<title>[\s\S]*?<\/title>/i, "<title>" + esc(title) + "</title>")
    .replace(/(<meta\s+name="description"\s+content=")[^"]*(")/i, (m, a, b) => a + esc(description) + b);

  fs.writeFileSync(path.join(ROOT, slug + ".html"), html);
  written.add(slug + ".html");
  console.log("wrote " + slug + ".html");
});

fs.readdirSync(ROOT)
  .filter((file) => file.endsWith(".html") && !written.has(file))
  .filter((file) => fs.readFileSync(path.join(ROOT, file), "utf8").includes(MARK))
  .forEach((file) => {
    fs.unlinkSync(path.join(ROOT, file));
    console.log("removed " + file);
  });
